[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sgm"
version = "0.1.0"
description = "Stability Generative Models"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
